### ISSUE TITLE
是否是和Ycm插件冲突？

### ISSUE THREAD

**Issue by snowwolf1** [dyng/ctrlsf.vim#110]
已经正常安装ag插件，且正常工作，然后在输入ctrlsf相关命令的时候就报错：
:CtrlSF LC_Actor_NPC
Error detected while processing function <SNR>53_SetOmnicompleteFunc..<SNR>53_
Pyeval:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcomplete
me.py", line 289, in NativeFiletypeCompletionUsable
    self.NativeFiletypeCompletionAvailable() )
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcomplete
me.py", line 284, in NativeFiletypeCompletionAvailable
    vimsupport.CurrentFiletypes() ] )
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcomplete
me.py", line 274, in FiletypeCompleterExistsForFiletype
    exists_completer = SendCompleterAvailableRequest( filetype )
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/comp
leter_available_request.py", line 57, in SendCompleterAvailableRequest
    request.Start()
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/comp
leter_available_request.py", line 41, in Start
    request_data = BuildRequestData()
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base
_request.py", line 167, in BuildRequestData
    request_data[ 'file_data' ] = vimsupport.GetUnsavedAndCurrentBufferData()

**Comment by snowwolf1** [comment]
Error detected while processing function <SNR>82_OnInsertLeave..<SNR>82_OnFileReadyToParse:
line   13:                                                                                                                                                                                          
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcompleteme.py", line 306, in OnFileReadyToParse
    self._latest_file_parse_request.Start()
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/event_notification.py", line 43, in Start
    request_data = BuildRequestData()
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 167, in BuildRequestData
    request_data[ 'file_data' ] = vimsupport.GetUnsavedAndCurrentBufferData()
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/vimsupport.py", line 126, in GetUnsavedAndCurrentBufferData
    'contents': '\n'.join( ToUnicode( x ) for x in buffer_object ) + '\n',
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/vimsupport.py", line 126, in <genexpr>
    'contents': '\n'.join( ToUnicode( x ) for x in buffer_object ) + '\n',
  File "/home/lhy/.vim/bundle/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/utils.py", line 96, in ToUnicode
    return str( value, 'utf8' )
  File "/home/lhy/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/python-future/src/future/types/newstr.py", line 97, in __new__
    value = args[0].decode(*args[1:], **kwargs)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc1 in position 17: invalid start byte
Error detected while processing function <SNR>82_OnInsertLeave:
line    7:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/youcompleteme.py", line 327, in OnInsertLeave
    SendEventNotificationAsync( 'InsertLeave' )
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/event_notification.py", line 79, in SendEventNotificationAsync
    event.Start()
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/event_notification.py", line 43, in Start
    request_data = BuildRequestData()
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/client/base_request.py", line 167, in BuildRequestData
    request_data[ 'file_data' ] = vimsupport.GetUnsavedAndCurrentBufferData()
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/vimsupport.py", line 126, in GetUnsavedAndCurrentBufferData
    'contents': '\n'.join( ToUnicode( x ) for x in buffer_object ) + '\n',
  File "/home/lhy/.vim/bundle/YouCompleteMe/autoload/../python/ycm/vimsupport.py", line 126, in <genexpr>
    'contents': '\n'.join( ToUnicode( x ) for x in buffer_object ) + '\n',
  File "/home/lhy/.vim/bundle/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/utils.py", line 96, in ToUnicode
    return str( value, 'utf8' )
  File "/home/lhy/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/python-future/src/future/types/newstr.py", line 97, in __new__
    value = args[0].decode(*args[1:], **kwargs)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc1 in position 17: invalid start byte

**Comment by dyng** [comment]
```
File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc1 in position 17: invalid start byte
Error detected while processing function 82_OnInsertLeave:
```

根据你的错误信息，推测可能你的文件中包含了一些python的utf8编码无法解码的字符。

**Comment by snowwolf1** [comment]
我看是ycm这个插件的python文件报错。我看了ycm文件确实是utf-8格式的。难道只能不用ycm这个插件了？

**Comment by dyng** [comment]
和ycm没有关系，是ycm在解析你的文件的内容时发生错误。因为ctrlsf会把搜索结果（也就是你的文件的内容）显示出来，ycm会去解析这些内容来获得补全的关键词，如果内容里面包含有非utf8的字节，解析就会出错。

我也在用ycm，并没有出现任何问题。

**Comment by snowwolf1** [comment]
非常感谢，我明白了，确实我源代码的保存的格式不是utf-8的。

**Comment by dyng** [comment]
不客气。如果问题已经解决，那我就把这个issue给关闭了。
